package com.zy.entities;

// Generated 2017-3-16 14:47:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TBook generated by hbm2java
 */
public class Book
{

	private String bid;
	private String bname;
	private String author;
	private BigDecimal price;
	private BigDecimal currPrice;
	private BigDecimal discount;
	private String press;
	private String publishtime;
	private Integer edition;
	private Integer pageNum;
	private Integer wordNum;
	private String printtime;
	private Integer booksize;
	private String paper;
	private String cid;
	private String imageW;
	private String imageB;
	private int orderBy;

	public Book()
	{
	}

	public Book(int orderBy)
	{
		this.orderBy = orderBy;
	}

	public Book(String bname, String author, BigDecimal price,
			BigDecimal currPrice, BigDecimal discount, String press,
			String publishtime, Integer edition, Integer pageNum,
			Integer wordNum, String printtime, Integer booksize, String paper,
			String cid, String imageW, String imageB, int orderBy)
	{
		this.bname = bname;
		this.author = author;
		this.price = price;
		this.currPrice = currPrice;
		this.discount = discount;
		this.press = press;
		this.publishtime = publishtime;
		this.edition = edition;
		this.pageNum = pageNum;
		this.wordNum = wordNum;
		this.printtime = printtime;
		this.booksize = booksize;
		this.paper = paper;
		this.cid = cid;
		this.imageW = imageW;
		this.imageB = imageB;
		this.orderBy = orderBy;
	}

	public String getBid()
	{
		return this.bid;
	}

	public void setBid(String bid)
	{
		this.bid = bid;
	}

	public String getBname()
	{
		return this.bname;
	}

	public void setBname(String bname)
	{
		this.bname = bname;
	}

	public String getAuthor()
	{
		return this.author;
	}

	public void setAuthor(String author)
	{
		this.author = author;
	}

	public BigDecimal getPrice()
	{
		return this.price;
	}

	public void setPrice(BigDecimal price)
	{
		this.price = price;
	}

	public BigDecimal getCurrPrice()
	{
		return this.currPrice;
	}

	public void setCurrPrice(BigDecimal currPrice)
	{
		this.currPrice = currPrice;
	}

	public BigDecimal getDiscount()
	{
		return this.discount;
	}

	public void setDiscount(BigDecimal discount)
	{
		this.discount = discount;
	}

	public String getPress()
	{
		return this.press;
	}

	public void setPress(String press)
	{
		this.press = press;
	}

	public String getPublishtime()
	{
		return this.publishtime;
	}

	public void setPublishtime(String publishtime)
	{
		this.publishtime = publishtime;
	}

	public Integer getEdition()
	{
		return this.edition;
	}

	public void setEdition(Integer edition)
	{
		this.edition = edition;
	}

	public Integer getPageNum()
	{
		return this.pageNum;
	}

	public void setPageNum(Integer pageNum)
	{
		this.pageNum = pageNum;
	}

	public Integer getWordNum()
	{
		return this.wordNum;
	}

	public void setWordNum(Integer wordNum)
	{
		this.wordNum = wordNum;
	}

	public String getPrinttime()
	{
		return this.printtime;
	}

	public void setPrinttime(String printtime)
	{
		this.printtime = printtime;
	}

	public Integer getBooksize()
	{
		return this.booksize;
	}

	public void setBooksize(Integer booksize)
	{
		this.booksize = booksize;
	}

	public String getPaper()
	{
		return this.paper;
	}

	public void setPaper(String paper)
	{
		this.paper = paper;
	}

	public String getCid()
	{
		return this.cid;
	}

	public void setCid(String cid)
	{
		this.cid = cid;
	}

	public String getImageW()
	{
		return this.imageW;
	}

	public void setImageW(String imageW)
	{
		this.imageW = imageW;
	}

	public String getImageB()
	{
		return this.imageB;
	}

	public void setImageB(String imageB)
	{
		this.imageB = imageB;
	}

	public int getOrderBy()
	{
		return this.orderBy;
	}

	public void setOrderBy(int orderBy)
	{
		this.orderBy = orderBy;
	}

}
