package com.zy.entities;

import java.math.BigDecimal;

// Generated 2017-3-25 17:18:54 by Hibernate Tools 3.4.0.CR1

/**
 * TCartitem generated by hbm2java
 */
public class Cartitem
{

	private String cartItemId;
	private Book book;
	private User user;
	private Integer quantity;
	private int orderBy;

	public Cartitem()
	{
	}

	public Cartitem(int orderBy)
	{
		this.orderBy = orderBy;
	}

	public Cartitem(String cartItemId, Book book, User user, Integer quantity)
	{
		super();
		this.cartItemId = cartItemId;
		this.book = book;
		this.user = user;
		this.quantity = quantity;
	}

	public String getCartItemId()
	{
		return cartItemId;
	}

	public void setCartItemId(String cartItemId)
	{
		this.cartItemId = cartItemId;
	}

	public Book getBook()
	{
		return book;
	}

	public void setBook(Book book)
	{
		this.book = book;
	}

	public User getUser()
	{
		return user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

	public Integer getQuantity()
	{
		return quantity;
	}

	public void setQuantity(Integer quantity)
	{
		this.quantity = quantity;
	}

	public int getOrderBy()
	{
		return orderBy;
	}

	public void setOrderBy(int orderBy)
	{
		this.orderBy = orderBy;
	}

	// 小计计算
	public double getSubTotal()
	{
		// 使用BigDecimal不会损失精度
		// 必须使用String类型的构造器
		BigDecimal bgCurrPrice = new BigDecimal(book.getCurrPrice() + "");
		BigDecimal bdQuantity = new BigDecimal(getQuantity() + "");
		BigDecimal r = bgCurrPrice.multiply(bdQuantity);
		return r.doubleValue();
	}
}
