package com.zy.entities;

// Generated 2017-3-29 21:05:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TOrderitem generated by hbm2java
 */
public class Orderitem 
{

	private String orderItemId;
	private Order order;
	private Integer quantity;
	private BigDecimal subtotal;
	private String bid;
	private String bname;
	private BigDecimal currPrice;
	private String imageB;

	public Orderitem()
	{
	}

	public Orderitem(String orderItemId)
	{
		this.orderItemId = orderItemId;
	}

	public Orderitem(String orderItemId, Order order, Integer quantity,
			BigDecimal subtotal, String bid, String bname,
			BigDecimal currPrice, String imageB)
	{
		super();
		this.orderItemId = orderItemId;
		this.order = order;
		this.quantity = quantity;
		this.subtotal = subtotal;
		this.bid = bid;
		this.bname = bname;
		this.currPrice = currPrice;
		this.imageB = imageB;
	}

	public String getOrderItemId()
	{
		return orderItemId;
	}

	public void setOrderItemId(String orderItemId)
	{
		this.orderItemId = orderItemId;
	}

	public Order getOrder()
	{
		return order;
	}

	public void setOrder(Order order)
	{
		this.order = order;
	}

	public Integer getQuantity()
	{
		return quantity;
	}

	public void setQuantity(Integer quantity)
	{
		this.quantity = quantity;
	}

	public BigDecimal getSubtotal()
	{
		return subtotal;
	}

	public void setSubtotal(BigDecimal subtotal)
	{
		this.subtotal = subtotal;
	}

	public String getBid()
	{
		return bid;
	}

	public void setBid(String bid)
	{
		this.bid = bid;
	}

	public String getBname()
	{
		return bname;
	}

	public void setBname(String bname)
	{
		this.bname = bname;
	}

	public BigDecimal getCurrPrice()
	{
		return currPrice;
	}

	public void setCurrPrice(BigDecimal currPrice)
	{
		this.currPrice = currPrice;
	}

	public String getImageB()
	{
		return imageB;
	}

	public void setImageB(String imageB)
	{
		this.imageB = imageB;
	}

}
